name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - features/gc-minimum2
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 379.0.0'
      - name: 'Upload test file'
        run: 'echo "test" > test.txt && gsutil cp test.txt gs://${{ secrets.GCP_BUCKET_NAME }}'