name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_WORKING_DIR: './terraform'

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform apply -auto-approve
